-- scripts/lib/TranZlator/icons.lua

-- Icons for notifications
local icons = {
    {name = "CHAR_ABIGAIL", display = "Abigail"},
    {name = "CHAR_AGENT14", display = "Agent 14"},
    {name = "CHAR_ALL_PLAYERS_CONF", display = "All Players Conf"},
    {name = "CHAR_AMANDA", display = "Amanda"},
    {name = "CHAR_AMMUNATION", display = "Ammunation"},
    {name = "CHAR_ANDREAS", display = "Andreas"},
    {name = "CHAR_ANTONIA", display = "Antonia"},
    {name = "CHAR_ARTHUR", display = "Arthur"},
    {name = "CHAR_ASHLEY", display = "Ashley"},
    {name = "CHAR_BANK_BOL", display = "Bank of Liberty"},
    {name = "CHAR_BARRY", display = "Barry"},
    {name = "CHAR_BEVERLY", display = "Beverly"},
    {name = "CHAR_MP_BRUCIE", display = "Brucie"},
    {name = "CHAR_CARSITE", display = "Carsite"},
    {name = "CHAR_CHEF", display = "Chef"},
    {name = "CHAR_CHENG", display = "Cheng"},
    {name = "CHAR_CHENGSR", display = "Cheng Sr."},
    {name = "CHAR_CHOP", display = "Chop"},
    {name = "CHAR_CRIS", display = "Cris"},
    {name = "CHAR_DAVE", display = "Dave"},
    {name = "CHAR_DEVIN", display = "Devin"},
    {name = "CHAR_DOM", display = "Dom"},
    {name = "CHAR_DREYFUSS", display = "Dreyfuss"},
    {name = "CHAR_MP_RAY_LAVOY", display = "Ray"},
    {name = "CHAR_ENGLISH_DAVE", display = "English Dave"},
    {name = "CHAR_EPSILON", display = "Epsilon"},
    {name = "CHAR_FLOYD", display = "Floyd"},
    {name = "CHAR_FRANKLIN", display = "Franklin"},
    {name = "CHAR_DR_FRIEDLANDER", display = "Friedlander"},
    {name = "CHAR_GAYMILITARY", display = "Gay Military"},
    {name = "CHAR_HAO", display = "Hao"},
    {name = "CHAR_HUNTER", display = "Hunter"},
    {name = "CHAR_JIMMY", display = "Jimmy"},
    {name = "CHAR_JOSEF", display = "Josef"},
    {name = "CHAR_JOSH", display = "Josh"},
    {name = "CHAR_LAMAR", display = "Lamar"},
    {name = "CHAR_LAZLOW", display = "Lazlow"},
    {name = "CHAR_LS_CUSTOMS", display = "LS Customs"},
    {name = "CHAR_LS_TOURIST_BOARD", display = "LS Tourist Board"},
    {name = "CHAR_LIFEINVADER", display = "Life Invader"},
    {name = "CHAR_LJT", display = "LJT"},
    {name = "CHAR_MANUEL", display = "Manuel"},
    {name = "CHAR_MARY_ANN", display = "Maryann"},
    {name = "CHAR_MAUDE", display = "Maude"},
    {name = "CHAR_MICHAEL", display = "Michael"},
    {name = "CHAR_MILSITE", display = "Milsite"},
    {name = "CHAR_MOLLY", display = "Molly"},
    {name = "CHAR_MP_ARMY_CONTACT", display = "MP Army Contact"},
    {name = "CHAR_MP_BIKER_BOSS", display = "MP Biker Boss"},
    {name = "CHAR_MP_FAM_BOSS", display = "MP Family Boss"},
    {name = "CHAR_MP_FIB_CONTACT", display = "MP FIB Contact"},
    {name = "CHAR_MP_MERRYWEATHER", display = "MP Merryweather"},
    {name = "CHAR_MP_ROBERTO", display = "MP Roberto"},
    {name = "CHAR_MP_SNITCH", display = "MP Snitch"},
    {name = "CHAR_MRS_THORNHILL", display = "Mrs. Thornhill"},
    {name = "CHAR_NIGEL", display = "Nigel"},
    {name = "CHAR_OMEGA", display = "Omega"},
    {name = "CHAR_ONEIL", display = "O'Neil"},
    {name = "CHAR_ORTEGA", display = "Ortega"},
    {name = "CHAR_PAIGE", display = "Paige"},
    {name = "CHAR_PEGASUS_DELIVERY", display = "Pegasus Delivery"},
    {name = "DIA_POPOV", display = "Popov"},
    {name = "CHAR_PROPERTY_ARMS_TRAFFICKING", display = "Property Arms Trafficking"},
    {name = "CHAR_PROPERTY_BAR_AIRPORT", display = "Property Bar Airport"},
    {name = "CHAR_PROPERTY_BAR_BAYVIEW", display = "Property Bar Bayview"},
    {name = "CHAR_PROPERTY_BAR_CAFE_ROJO", display = "Property Bar Cafe Rojo"},
    {name = "CHAR_PROPERTY_BAR_COCKOTOOS", display = "Property Bar Cockotoos"},
    {name = "CHAR_PROPERTY_BAR_ECLIPSE", display = "Property Bar Eclipse"},
    {name = "CHAR_PROPERTY_BAR_FES", display = "Property Bar Fes"},
    {name = "CHAR_PROPERTY_BAR_HOOKIES", display = "Property Bar Hookies"},
    {name = "CHAR_PROPERTY_BAR_IRISH", display = "Property Bar Irish"},
    {name = "CHAR_PROPERTY_BAR_LES_BIANCO", display = "Property Bar Les Bianco"},
    {name = "CHAR_PROPERTY_BAR_PITCHERS", display = "Property Bar Pitchers"},
    {name = "CHAR_PROPERTY_BAR_TEQUILALA", display = "Property Bar Tequilala"},
    {name = "CHAR_PROPERTY_CAR_MOD_SHOP", display = "Property Car Mod Shop"},
    {name = "CHAR_PROPERTY_CINEMA_DOWNTOWN", display = "Property Cinema Downtown"},
    {name = "CHAR_PROPERTY_CINEMA_MORNINGWOOD", display = "Property Cinema Morningwood"},
    {name = "CHAR_PROPERTY_CINEMA_VINEWOOD", display = "Property Cinema Vinewood"},
    {name = "CHAR_PROPERTY_GOLF_CLUB", display = "Property Golf Club"},
    {name = "CHAR_PROPERTY_SONAR_COLLECTIONS", display = "Property Sonar Collections"},
    {name = "CHAR_PROPERTY_TAXI_LOT", display = "Property Taxi Lot"},
    {name = "CHAR_PROPERTY_TOWING_IMPOUND", display = "Property Towing Impound"},
    {name = "CHAR_PROPERTY_WEED_SHOP", display = "Property Weed Shop"},
    {name = "CHAR_RON", display = "Ron"},
    {name = "CHAR_SAEEDA", display = "Saeeda"},
    {name = "CHAR_SIMEON", display = "Simeon"},
    {name = "CHAR_SOCIAL_CLUB", display = "Social Club"},
    {name = "CHAR_SOLOMON", display = "Solomon"},
    {name = "CHAR_STEVE", display = "Steve"},
    {name = "CHAR_STRETCH", display = "Stretch"},
    {name = "CHAR_MP_STRIPCLUB_PR", display = "Strip Club PR"},
    {name = "CHAR_STRIPPER_CHASTITY", display = "Stripper Chastity"},
    {name = "CHAR_STRIPPER_CHEETAH", display = "Stripper Cheetah"},
    {name = "CHAR_STRIPPER_FUFU", display = "Stripper Fufu"},
    {name = "CHAR_STRIPPER_INFERNUS", display = "Stripper Infernus"},
    {name = "CHAR_STRIPPER_JULIET", display = "Stripper Juliet"},
    {name = "CHAR_STRIPPER_NIKKI", display = "Stripper Nikki"},
    {name = "CHAR_STRIPPER_PEACH", display = "Stripper Peach"},
    {name = "CHAR_STRIPPER_SAPPHIRE", display = "Stripper Sapphire"},
    {name = "CHAR_TANISHA", display = "Tanisha"},
    {name = "CHAR_TAXI", display = "Taxi"},
    {name = "CHAR_TENNIS_COACH", display = "Tennis Coach"},
    {name = "CHAR_TOM", display = "Tom"},
    {name = "CHAR_TONY_PRINCE", display = "Tony Prince"},
    {name = "CHAR_TOW_TONYA", display = "Tow Tonya"},
    {name = "CHAR_TRACEY", display = "Tracey"},
    {name = "CHAR_TREVOR", display = "Trevor"},
    {name = "CHAR_WADE", display = "Wade"},
    {name = "CHAR_WENDY", display = "Wendy"},
    {name = "CHAR_YOUTUBE", display = "YouTube"}
}

return icons
