-- language_extension.lua

local extendedLanguages = {
    {code="af", name="Afrikaans"},
    {code="sq", name="Albanian"},
    {code="am", name="Amharic"},
    {code="ar", name="Arabic"},
    {code="hy", name="Armenian"},
    {code="az", name="Azerbaijani"},
    {code="eu", name="Basque"},
    {code="be", name="Belarusian"},
    {code="bn", name="Bengali"},
    {code="bs", name="Bosnian"},
    {code="bg", name="Bulgarian"},
    {code="ca", name="Catalan"},
    {code="ceb", name="Cebuano"},
    {code="ny", name="Chichewa"},
    {code="zh", name="Chinese"},
    {code="co", name="Corsican"},
    {code="hr", name="Croatian"},
    {code="cs", name="Czech"},
    {code="da", name="Danish"},
    {code="nl", name="Dutch"},
    {code="en", name="English"},
    {code="eo", name="Esperanto"},
    {code="et", name="Estonian"},
    {code="tl", name="Filipino"},
    {code="fi", name="Finnish"},
    {code="fr", name="French"},
    {code="fy", name="Frisian"},
    {code="gl", name="Galician"},
    {code="ka", name="Georgian"},
    {code="de", name="German"},
    {code="el", name="Greek"},
    {code="gu", name="Gujarati"},
    {code="ht", name="Haitian Creole"},
    {code="ha", name="Hausa"},
    {code="haw", name="Hawaiian"},
    {code="he", name="Hebrew"},
    {code="hi", name="Hindi"},
    {code="hmn", name="Hmong"},
    {code="hu", name="Hungarian"},
    {code="is", name="Icelandic"},
    {code="ig", name="Igbo"},
    {code="id", name="Indonesian"},
    {code="ga", name="Irish"},
    {code="it", name="Italian"},
    {code="ja", name="Japanese"},
    {code="jw", name="Javanese"},
    {code="kn", name="Kannada"},
    {code="kk", name="Kazakh"},
    {code="km", name="Khmer"},
    {code="rw", name="Kinyarwanda"},
    {code="ko", name="Korean"},
    {code="ku", name="Kurdish (Kurmanji)"},
    {code="ky", name="Kyrgyz"},
    {code="lo", name="Lao"},
    {code="la", name="Latin"},
    {code="lv", name="Latvian"},
    {code="lt", name="Lithuanian"},
    {code="lb", name="Luxembourgish"},
    {code="mk", name="Macedonian"},
    {code="mg", name="Malagasy"},
    {code="ms", name="Malay"},
    {code="ml", name="Malayalam"},
    {code="mt", name="Maltese"},
    {code="mi", name="Maori"},
    {code="mr", name="Marathi"},
    {code="mn", name="Mongolian"},
    {code="my", name="Myanmar (Burmese)"},
    {code="ne", name="Nepali"},
    {code="no", name="Norwegian"},
    {code="or", name="Odia (Oriya)"},
    {code="ps", name="Pashto"},
    {code="fa", name="Persian"},
    {code="pl", name="Polish"},
    {code="pt", name="Portuguese"},
    {code="pa", name="Punjabi"},
    {code="ro", name="Romanian"},
    {code="ru", name="Russian"},
    {code="sm", name="Samoan"},
    {code="gd", name="Scots Gaelic"},
    {code="sr", name="Serbian"},
    {code="st", name="Sesotho"},
    {code="sn", name="Shona"},
    {code="sd", name="Sindhi"},
    {code="si", name="Sinhala"},
    {code="sk", name="Slovak"},
    {code="sl", name="Slovenian"},
    {code="so", name="Somali"},
    {code="es", name="Spanish"},
    {code="su", name="Sundanese"},
    {code="sw", name="Swahili"},
    {code="sv", name="Swedish"},
    {code="tg", name="Tajik"},
    {code="ta", name="Tamil"},
    {code="tt", name="Tatar"},
    {code="te", name="Telugu"},
    {code="th", name="Thai"},
    {code="tr", name="Turkish"},
    {code="tk", name="Turkmen"},
    {code="uk", name="Ukrainian"},
    {code="ur", name="Urdu"},
    {code="ug", name="Uyghur"},
    {code="uz", name="Uzbek"},
    {code="vi", name="Vietnamese"},
    {code="cy", name="Welsh"},
    {code="xh", name="Xhosa"},
    {code="yi", name="Yiddish"},
    {code="yo", name="Yoruba"},
    {code="zu", name="Zulu"},
    {code="ace", name="Achinese"},
    {code="ach", name="Acoli"},
    {code="ada", name="Adangme"},
    {code="ady", name="Adyghe"},
    {code="aa", name="Afar"},
    {code="ab", name="Abkhazian"},
    {code="afh", name="Afrihili"},
    {code="agq", name="Aghem"},
    {code="ain", name="Ainu"},
    {code="ak", name="Akan"},
    {code="bss", name="Akoose"},
    {code="akz", name="Alabama"},
    {code="sq", name="Albanian"},
    {code="ase", name="American Sign Language"},
    {code="anp", name="Angika"},
    {code="arq", name="Algerian Arabic"},
    {code="rup", name="Aromanian"},
    {code="frp", name="Arpitan"},
    {code="ast", name="Asturian"},
    {code="asa", name="Asu"},
    {code="cch", name="Atsam"},
    {code="awa", name="Awadhi"},
    {code="ay", name="Aymara"},
    {code="bfq", name="Badaga"},
    {code="bqi", name="Bakhtiari"},
    {code="bgn", name="Baluchi"},
    {code="bba", name="Baatonum"},
    {code="bm", name="Bambara"},
    {code="bax", name="Bamun"},
    {code="bjn", name="Banjar"},
    {code="bbc", name="Batak Toba"},
    {code="bar", name="Bavarian"},
    {code="bej", name="Beja"},
    {code="bem", name="Bemba"},
    {code="bez", name="Bena"},
    {code="bew", name="Betawi"},
    {code="bho", name="Bhojpuri"},
    {code="bik", name="Bikol"},
    {code="bin", name="Bini"},
    {code="bpy", name="Bishnupriya"},
    {code="bi", name="Bislama"},
    {code="byn", name="Blin"},
    {code="brx", name="Bodo"},
    {code="brh", name="Brahui"},
    {code="bra", name="Braj"},
    {code="br", name="Breton"},
    {code="bug", name="Buginese"},
    {code="bg", name="Bulgarian"},
    {code="bum", name="Bulu"},
    {code="bua", name="Buriat"},
    {code="my", name="Burmese"},
    {code="cad", name="Caddo"},
    {code="frc", name="Cajun French"},
    {code="cps", name="Capiznon"},
    {code="car", name="Carib"},
    {code="ca", name="Catalan"},
    {code="cay", name="Cayuga"},
    {code="ceb", name="Cebuano"},
    {code="dtp", name="Central Dusun"},
    {code="esu", name="Central Yupik"},
    {code="ch", name="Chamorro"},
    {code="ce", name="Chechen"},
    {code="chr", name="Cherokee"},
    {code="chy", name="Cheyenne"},
    {code="chb", name="Chibcha"},
    {code="cgg", name="Chiga"},
    {code="qug", name="Chimborazo Highland Quichua"},
    {code="zh", name="Chinese"},
    {code="chn", name="Chinook Jargon"},
    {code="chp", name="Chipewyan"},
    {code="cho", name="Choctaw"},
    {code="cu", name="Church Slavic"},
    {code="chk", name="Chuukese"},
    {code="cv", name="Chuvash"},
    {code="ksh", name="Colognian"},
    {code="swb", name="Comorian"},
    {code="cop", name="Coptic"},
    {code="kw", name="Cornish"},
    {code="co", name="Corsican"},
    {code="mus", name="Creek"},
    {code="crh", name="Crimean Turkish"},
    {code="hr", name="Croatian"},
    {code="cs", name="Czech"},
    {code="dak", name="Dakota"},
    {code="da", name="Danish"},
    {code="dar", name="Dargwa"},
    {code="dzg", name="Dazaga"},
    {code="del", name="Delaware"},
    {code="din", name="Dinka"},
    {code="dv", name="Divehi"},
    {code="doi", name="Dogri"},
    {code="dgr", name="Dogrib"},
    {code="dua", name="Duala"},
    {code="nl", name="Dutch"},
    {code="dyu", name="Dyula"},
    {code="dz", name="Dzongkha"},
    {code="frs", name="Eastern Frisian"},
    {code="efi", name="Efik"},
    {code="arz", name="Egyptian Arabic"},
    {code="eka", name="Ekajuk"},
    {code="elx", name="Elamite"},
    {code="ebu", name="Embu"},
    {code="egl", name="Emilian"},
    {code="en", name="English"},
    {code="myv", name="Erzya"},
    {code="eo", name="Esperanto"},
    {code="et", name="Estonian"},
    {code="gez", name="Geez"},
    {code="efi", name="Efik"},
    {code="ee", name="Ewe"},
    {code="ewo", name="Ewondo"},
    {code="fo", name="Faroese"},
    {code="fat", name="Fanti"},
    {code="fj", name="Fijian"},
    {code="fil", name="Filipino"},
    {code="fi", name="Finnish"},
    {code="fit", name="Tornedalen Finnish"},
    {code="fr", name="French"},
    {code="fur", name="Friulian"},
    {code="ff", name="Fulah"},
    {code="gaa", name="Ga"},
    {code="gl", name="Galician"},
    {code="gan", name="Gan Chinese"},
    {code="lg", name="Ganda"},
    {code="gez", name="Geez"},
    {code="ka", name="Georgian"},
    {code="de", name="German"},
    {code="aln", name="Gheg Albanian"},
    {code="bbj", name="Ghomala"},
    {code="glk", name="Gilaki"},
    {code="gil", name="Gilbertese"},
    {code="gom", name="Goan Konkani"},
    {code="gon", name="Gondi"},
    {code="gor", name="Gorontalo"},
    {code="got", name="Gothic"},
    {code="grb", name="Grebo"},
    {code="el", name="Greek"},
    {code="grn", name="Guarani"},
    {code="gu", name="Gujarati"},
    {code="guz", name="Gusii"},
    {code="gwi", name="Gwichʼin"},
    {code="hai", name="Haida"},
    {code="ht", name="Haitian"},
    {code="hak", name="Hakka Chinese"},
    {code="ha", name="Hausa"},
    {code="haw", name="Hawaiian"},
    {code="he", name="Hebrew"},
    {code="hz", name="Herero"},
    {code="hil", name="Hiligaynon"},
    {code="hi", name="Hindi"},
    {code="ho", name="Hiri Motu"},
    {code="hit", name="Hittite"},
    {code="hmn", name="Hmong"},
    {code="hu", name="Hungarian"},
    {code="hup", name="Hupa"},
    {code="iba", name="Iban"},
    {code="ibb", name="Ibibio"},
    {code="io", name="Ido"},
    {code="ig", name="Igbo"},
    {code="ilo", name="Iloko"},
    {code="smn", name="Inari Sami"},
    {code="id", name="Indonesian"},
    {code="izh", name="Ingrian"},
    {code="inh", name="Ingush"},
    {code="ia", name="Interlingua"},
    {code="ie", name="Interlingue"},
    {code="iu", name="Inuktitut"},
    {code="ik", name="Inupiaq"},
    {code="ga", name="Irish"},
    {code="is", name="Icelandic"},
    {code="it", name="Italian"},
    {code="jam", name="Jamaican Creole English"},
    {code="ja", name="Japanese"},
    {code="jv", name="Javanese"},
    {code="kaj", name="Jju"},
    {code="dyo", name="Jola-Fonyi"},
    {code="jrb", name="Judeo-Arabic"},
    {code="jpr", name="Judeo-Persian"},
    {code="jut", name="Jutish"},
    {code="kbd", name="Kabardian"},
    {code="kab", name="Kabyle"},
    {code="kea", name="Kabuverdianu"},
    {code="kac", name="Kachin"},
    {code="kkj", name="Kako"},
    {code="kl", name="Kalaallisut"},
    {code="kln", name="Kalenjin"},
    {code="xal", name="Kalmyk"},
    {code="kam", name="Kamba"},
    {code="kbl", name="Kanembu"},
    {code="kn", name="Kannada"},
    {code="kr", name="Kanuri"},
    {code="krc", name="Karachay-Balkar"},
    {code="kaa", name="Kara-Kalpak"},
    {code="krl", name="Karelian"},
    {code="ks", name="Kashmiri"},
    {code="csb", name="Kashubian"},
    {code="kaw", name="Kawi"},
    {code="kk", name="Kazakh"},
    {code="ken", name="Kenyang"},
    {code="kha", name="Khasi"},
    {code="km", name="Khmer"},
    {code="kho", name="Khotanese"},
    {code="khw", name="Khowar"},
    {code="ki", name="Kikuyu"},
    {code="kmb", name="Kimbundu"},
    {code="krj", name="Kinaray-a"},
    {code="rw", name="Kinyarwanda"},
    {code="kiu", name="Kirmanjki"},
    {code="tlh", name="Klingon"},
    {code="kv", name="Komi"},
    {code="koi", name="Komi-Permyak"},
    {code="kg", name="Kongo"},
    {code="kok", name="Konkani"},
    {code="kos", name="Kosraean"},
    {code="avk", name="Kotava"},
    {code="khq", name="Koyra Chiini"},
    {code="ses", name="Koyraboro Senni"},
    {code="kpe", name="Kpelle"},
    {code="kri", name="Krio"},
    {code="kj", name="Kuanyama"},
    {code="kum", name="Kumyk"},
    {code="kru", name="Kurukh"},
    {code="kut", name="Kutenai"},
    {code="nmg", name="Kwasio"},
    {code="lad", name="Ladino"},
    {code="lah", name="Lahnda"},
    {code="lkt", name="Lakota"},
    {code="lam", name="Lamba"},
    {code="lag", name="Langi"},
    {code="lo", name="Lao"},
    {code="ltg", name="Latgalian"},
    {code="la", name="Latin"},
    {code="lv", name="Latvian"},
    {code="lzz", name="Laz"},
    {code="lez", name="Lezghian"},
    {code="lij", name="Ligurian"},
    {code="li", name="Limburgish"},
    {code="ln", name="Lingala"},
    {code="lfn", name="Lingua Franca Nova"},
    {code="lzh", name="Literary Chinese"},
    {code="lt", name="Lithuanian"},
    {code="liv", name="Livonian"},
    {code="jbo", name="Lojban"},
    {code="lmo", name="Lombard"},
    {code="nds", name="Low German"},
    {code="sli", name="Lower Silesian"},
    {code="dsb", name="Lower Sorbian"},
    {code="loz", name="Lozi"},
    {code="lu", name="Luba-Katanga"},
    {code="lua", name="Luba-Lulua"},
    {code="lui", name="Luiseno"},
    {code="smj", name="Lule Sami"},
    {code="lun", name="Lunda"},
    {code="luo", name="Luo"},
    {code="lus", name="Mizo"},
    {code="lb", name="Luxembourgish"},
    {code="luy", name="Luyia"},
    {code="mde", name="Maba"},
    {code="mk", name="Macedonian"},
    {code="jmc", name="Machame"},
    {code="mad", name="Madurese"},
    {code="maf", name="Mafa"},
    {code="mag", name="Magahi"},
    {code="vmf", name="Main-Franconian"},
    {code="mai", name="Maithili"},
    {code="mak", name="Makasar"},
    {code="mgh", name="Makhuwa-Meetto"},
    {code="kde", name="Makonde"},
    {code="mku", name="Kuna"},
    {code="mg", name="Malagasy"},
    {code="ms", name="Malay"},
    {code="ml", name="Malayalam"},
    {code="mt", name="Maltese"},
    {code="mnc", name="Manchu"},
    {code="mdr", name="Mandar"},
    {code="man", name="Mandingo"},
    {code="mni", name="Manipuri"},
    {code="gv", name="Manx"},
    {code="mi", name="Maori"},
    {code="arn", name="Mapuche"},
    {code="mr", name="Marathi"},
    {code="chm", name="Mari"},
    {code="mh", name="Marshallese"},
    {code="mwr", name="Marwari"},
    {code="mas", name="Masai"},
    {code="mzn", name="Mazanderani"},
    {code="byv", name="Medumba"},
    {code="men", name="Mende"},
    {code="mwv", name="Mentawai"},
    {code="mer", name="Meru"},
    {code="mgo", name="Meta’"},
    {code="mic", name="Mi'kmaq"},
    {code="dum", name="Middle Dutch"},
    {code="enm", name="Middle English"},
    {code="frm", name="Middle French"},
    {code="gmh", name="Middle High German"},
    {code="mga", name="Middle Irish"},
    {code="nan", name="Min Nan Chinese"},
    {code="xmf", name="Mingrelian"},
    {code="mwl", name="Mirandese"},
    {code="lus", name="Mizo"},
    {code="ar", name="Modern Standard Arabic"},
    {code="mdf", name="Moksha"},
    {code="ro_MD", name="Moldavian"},
    {code="lol", name="Mongo"},
    {code="mn", name="Mongolian"},
    {code="ary", name="Moroccan Arabic"},
    {code="mos", name="Mossi"},
    {code="mul", name="Multiple Languages"},
    {code="mua", name="Mundang"},
    {code="ttt", name="Muslim Tat"},
    {code="mye", name="Myene"},
    {code="naq", name="Nama"},
    {code="na", name="Nauru"},
    {code="nv", name="Navajo"},
    {code="ng", name="Ndonga"},
    {code="nap", name="Neapolitan"},
    {code="ne", name="Nepali"},
    {code="new", name="Newari"},
    {code="sba", name="Ngambay"},
    {code="nnh", name="Ngiemboon"},
    {code="jgo", name="Ngomba"},
    {code="yrl", name="Nheengatu"},
    {code="nia", name="Nias"},
    {code="niu", name="Niuean"},
    {code="zxx", name="No linguistic content"},
    {code="nog", name="Nogai"},
    {code="nd", name="North Ndebele"},
    {code="frr", name="Northern Frisian"},
    {code="se", name="Northern Sami"},
    {code="nso", name="Northern Sotho"},
    {code="no", name="Norwegian"},
    {code="nb", name="Norwegian Bokmål"},
    {code="nn", name="Norwegian Nynorsk"},
    {code="nov", name="Novial"},
    {code="nus", name="Nuer"},
    {code="nym", name="Nyamwezi"},
    {code="nyn", name="Nyankole"},
    {code="tog", name="Nyasa Tonga"},
    {code="ny", name="Nyanja"},
    {code="nyo", name="Nyoro"},
    {code="nzi", name="Nzima"},
    {code="nqo", name="N’Ko"},
    {code="oj", name="Ojibwa"},
    {code="oc", name="Occitan"},
    {code="oj", name="Odawa"},
    {code="or", name="Odia"},
    {code="om", name="Oromo"},
    {code="osa", name="Osage"},
    {code="os", name="Ossetic"},
    {code="pal", name="Pahlavi"},
    {code="pfl", name="Palatine German"},
    {code="pau", name="Palauan"},
    {code="pi", name="Pali"},
    {code="pam", name="Pampanga"},
    {code="pag", name="Pangasinan"},
    {code="pap", name="Papiamento"},
    {code="ps", name="Pashto"},
    {code="pdc", name="Pennsylvania German"},
    {code="fa", name="Persian"},
    {code="phn", name="Phoenician"},
    {code="pcd", name="Picard"},
    {code="pms", name="Piedmontese"},
    {code="pdt", name="Plautdietsch"},
    {code="pon", name="Pohnpeian"},
    {code="pnt", name="Pontic"},
    {code="pl", name="Polish"},
    {code="pms", name="Piedmontese"},
    {code="pt", name="Portuguese"},
    {code="pqm", name="Maliseet-Passamaquoddy"},
    {code="prg", name="Prussian"},
    {code="quc", name="Kʼicheʼ"},
    {code="qu", name="Quechua"},
    {code="ksh", name="Ripuarian"},
    {code="ro", name="Romanian"},
    {code="rm", name="Romansh"},
    {code="rof", name="Rombo"},
    {code="rtm", name="Rotuman"},
    {code="rug", name="Roviana"},
    {code="rn", name="Rundi"},
    {code="ru", name="Russian"},
    {code="rue", name="Rusyn"},
    {code="rwk", name="Rwa"},
    {code="ssy", name="Saho"},
    {code="sah", name="Yakut"},
    {code="sam", name="Samaritan Aramaic"},
    {code="saq", name="Samburu"},
    {code="sgs", name="Samogitian"},
    {code="sm", name="Samoan"},
    {code="sad", name="Sandawe"},
    {code="sg", name="Sango"},
    {code="sbp", name="Sangu"},
    {code="sa", name="Sanskrit"},
    {code="sat", name="Santali"},
    {code="sc", name="Sardinian"},
    {code="sas", name="Sasak"},
    {code="sdc", name="Sassarese Sardinian"},
    {code="stq", name="Saterland Frisian"},
    {code="saz", name="Saurashtra"},
    {code="sco", name="Scots"},
    {code="gd", name="Scottish Gaelic"},
    {code="sly", name="Selayar"},
    {code="sel", name="Selkup"},
    {code="seh", name="Sena"},
    {code="see", name="Seneca"},
    {code="sr", name="Serbian"},
    {code="sh", name="Serbo-Croatian"},
    {code="srr", name="Serer"},
    {code="sei", name="Seri"},
    {code="ksb", name="Shambala"},
    {code="shn", name="Shan"},
    {code="sn", name="Shona"},
    {code="sid", name="Sidamo"},
    {code="bla", name="Siksika"},
    {code="szl", name="Silesian"},
    {code="zh_Hans", name="Simplified Chinese"},
    {code="sd", name="Sindhi"},
    {code="si", name="Sinhala"},
    {code="sms", name="Skolt Sami"},
    {code="den", name="Slave"},
    {code="sk", name="Slovak"},
    {code="sl", name="Slovenian"},
    {code="xog", name="Soga"},
    {code="sog", name="Sogdien"},
    {code="so", name="Somali"},
    {code="snk", name="Soninke"},
    {code="azb", name="South Azerbaijani"},
    {code="nr", name="South Ndebele"},
    {code="alt", name="Southern Altai"},
    {code="st", name="Southern Sotho"},
    {code="es", name="Spanish"},
    {code="srn", name="Sranan Tongo"},
    {code="zgh", name="Standard Moroccan Tamazight"},
    {code="suk", name="Sukuma"},
    {code="sux", name="Sumerian"},
    {code="su", name="Sundanese"},
    {code="sus", name="Susu"},
    {code="sw", name="Swahili"},
    {code="ss", name="Swati"},
    {code="sv", name="Swedish"},
    {code="gsw", name="Swiss German"},
    {code="syr", name="Syriac"},
    {code="shi", name="Tachelhit"},
    {code="ty", name="Tahitian"},
    {code="taj", name="Tajiki"},
    {code="tg", name="Tajik"},
    {code="tzm", name="Tamazight"},
    {code="tly", name="Talysh"},
    {code="tmh", name="Tamashek"},
    {code="ta", name="Tamil"},
    {code="trv", name="Taroko"},
    {code="twq", name="Tasawaq"},
    {code="ttt", name="Tat"},
    {code="te", name="Telugu"},
    {code="tem", name="Temne"},
    {code="teo", name="Teso"},
    {code="tet", name="Tetum"},
    {code="th", name="Thai"},
    {code="bo", name="Tibetan"},
    {code="tig", name="Tigre"},
    {code="ti", name="Tigrinya"},
    {code="tem", name="Timne"},
    {code="tiv", name="Tiv"},
    {code="tli", name="Tlingit"},
    {code="tpi", name="Tok Pisin"},
    {code="tkl", name="Tokelau"},
    {code="tog", name="Tonga (Nyasa)"},
    {code="to", name="Tongan"},
    {code="fit", name="Tornedalen Finnish"},
    {code="tsi", name="Tsimshian"},
    {code="ts", name="Tsonga"},
    {code="tn", name="Tswana"},
    {code="tum", name="Tumbuka"},
    {code="aeb", name="Tunisian Arabic"},
    {code="tr", name="Turkish"},
    {code="tk", name="Turkmen"},
    {code="tru", name="Turoyo"},
    {code="tvl", name="Tuvalu"},
    {code="tyv", name="Tuvan"},
    {code="tw", name="Twi"},
    {code="kcg", name="Tyap"},
    {code="udm", name="Udmurt"},
    {code="uga", name="Ugaritic"},
    {code="uk", name="Ukrainian"},
    {code="umb", name="Umbundu"},
    {code="ur", name="Urdu"},
    {code="ug", name="Uyghur"},
    {code="uz", name="Uzbek"},
    {code="vai", name="Vai"},
    {code="ve", name="Venda"},
    {code="vec", name="Venetian"},
    {code="vep", name="Veps"},
    {code="vi", name="Vietnamese"},
    {code="vo", name="Volapük"},
    {code="vro", name="Võro"},
    {code="vot", name="Votic"},
    {code="vun", name="Vunjo"},
    {code="wa", name="Walloon"},
    {code="wae", name="Walser"},
    {code="war", name="Waray"},
    {code="wbp", name="Warlpiri"},
    {code="was", name="Washo"},
    {code="guc", name="Wayuu"},
    {code="cy", name="Welsh"},
    {code="vls", name="West Flemish"},
    {code="fy", name="Western Frisian"},
    {code="mrj", name="Western Mari"},
    {code="wal", name="Wolaytta"},
    {code="wo", name="Wolof"},
    {code="wuu", name="Wu Chinese"},
    {code="xh", name="Xhosa"},
    {code="hsn", name="Xiang Chinese"},
    {code="yav", name="Yangben"},
    {code="yao", name="Yao"},
    {code="yap", name="Yapese"},
    {code="ybb", name="Yemba"},
    {code="yi", name="Yiddish"},
    {code="yo", name="Yoruba"},
    {code="zap", name="Zapotec"},
    {code="dje", name="Zarma"},
    {code="zza", name="Zaza"},
    {code="zea", name="Zeelandic"},
    {code="zen", name="Zenaga"},
    {code="za", name="Zhuang"},
    {code="gbz", name="Zoroastrian Dari"},
    {code="zu", name="Zulu"},
    {code="zun", name="Zuni"}
}


-- Debugging-Ausgabe der Sprachentabelle
for i, lang in ipairs(languages) do
    if lang == nil then
        print("Nil entry in languages table at index " .. tostring(i))
    elseif lang.code == nil then
        print("Nil code in languages table at index " .. tostring(i))
    elseif lang.name == nil then
        print("Nil name in languages table at index " .. tostring(i))
    else
        print("Loaded language: " .. lang.name .. " with code: " .. lang.code)
    end
end

-- Funktion, um die Sprachenliste zu erweitern
local function extendLanguages(newLanguages)
    if not newLanguages or type(newLanguages) ~= "table" then
        error("extendLanguages called with invalid argument")
    end

    for _, lang in ipairs(newLanguages) do
        if lang and lang.code and lang.name then
            table.insert(languages, lang)
        else
            error("Invalid language entry detected in extendLanguages")
        end
    end
end

-- Funktion, um die Sprachenliste zurückzugeben
local function getLanguages()
    return languages
end

-- Exportiere die Funktionen und Daten
return {
    getLanguages = getLanguages,
    extendLanguages = extendLanguages
}